	language: python
python:
  - "3.6"
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg
install:
  - pip install -r requirements.txt
script:
  - python encrypt.py
  - python decrypt.py